gnome-terminal -x bash -c "./run-sh/run-mnist-01.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-02.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-03.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-04.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-05.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-06.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-07.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-08.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-09.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-mnist-10.sh;exec bash;"
gnome-terminal -x bash -c "source /etc/profile;~/anaconda3/envs/torch1.6/bin/python3 /data/jcliu/RE-AFL/mnist_server_thread.py --world_size 10 --dataset_type CIFAR10 --model_type Deep --rank 0;exec bash;"
